version: "3.9"
services:
  booking_app:
    build: .
    ports:
      - "8000:8000"
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/src
    entrypoint: ["sh", "entrypoint.sh"]
    depends_on:
      - booking_db
  booking_db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/booking_data
volumes:
  postgres_data:
