# Generated by Django 4.2.2 on 2023-06-29 09:13

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(max_length=4, unique=True)),
                ("cost_per_day", models.DecimalField(decimal_places=2, max_digits=7)),
                ("beds_numder", models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_start", models.DateTimeField()),
                ("book_end", models.DateTimeField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.fields.NOT_PROVIDED,
                        to="booking.room",
                    ),
                ),
            ],
        ),
    ]
