# Generated by Django 4.2.2 on 2023-06-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_alter_booking_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="book_end",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="book_start",
            field=models.DateField(),
        ),
    ]
